// Save in-game, reload the page, and resume via "Continue" on the title screen.
import { chromium, devices } from 'playwright';
const base = process.env.BASE || 'http://127.0.0.1:5173/';
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices['iPad Pro 11'] });
const p = await ctx.newPage();
const errs = [];
p.on('pageerror', e => errs.push('pageerror: ' + e.message));
p.on('dialog', d => d.accept());
await p.goto(base);
await p.waitForSelector('[data-m="new"]');
await p.tap('[data-m="new"]'); await p.tap('[data-m="next"]');
await p.waitForSelector('[data-m="site"]', { timeout: 20000 }); await p.tap('[data-m="site"]');
await p.waitForSelector('[data-m="go"]'); await p.tap('[data-m="go"]');
await p.waitForFunction(() => window.__game?.world);
await p.evaluate(() => window.__game.setSpeed(4));
await p.waitForTimeout(4000);
await p.tap('#tab-more'); await p.tap('[data-a="w:save"]'); await p.waitForTimeout(800);
const before = await p.evaluate(() => { const g = window.__game; return { tick: g.world.tick, cols: g.world.colonists(g.faction).map(c => c.name.nick).join(','), colony: g.world.playerByFaction(g.faction).colonyName }; });
await p.reload();
await p.waitForSelector('[data-m="continue"]', { timeout: 10000 });
const label = await p.textContent('[data-m="continue"]');
await p.tap('[data-m="continue"]');
await p.waitForFunction(() => window.__game?.world);
await p.waitForTimeout(800);
const after = await p.evaluate(() => { const g = window.__game; return { tick: g.world.tick, cols: g.world.colonists(g.faction).map(c => c.name.nick).join(','), colony: g.world.playerByFaction(g.faction).colonyName }; });
console.log('continue button:', label.trim());
console.log('before', JSON.stringify(before));
console.log('after ', JSON.stringify(after));
await p.screenshot({ path: 'test-output/continue.png' });
console.log(errs.join('\n') || 'no errors');
await b.close();
