import { chromium, devices } from 'playwright';
const [,, out = 'test-output/play.png', dev = 'iPad Pro 11', waitMs = '3000'] = process.argv;
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices[dev] });
const p = await ctx.newPage();
const errs = [];
p.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.type() + ': ' + m.text()); });
p.on('pageerror', e => errs.push('pageerror: ' + e.message + '\n' + e.stack));
await p.goto('http://127.0.0.1:5173/');
await p.waitForSelector('[data-m="new"]', { timeout: 20000 });
await p.screenshot({ path: out.replace('.png', '-menu.png') });
await p.tap('[data-m="new"]');
await p.waitForSelector('[data-m="next"]');
await p.screenshot({ path: out.replace('.png', '-setup.png') });
await p.tap('[data-m="next"]');
await p.waitForSelector('[data-m="site"]', { timeout: 20000 });
await p.screenshot({ path: out.replace('.png', '-crew.png') });
await p.tap('[data-m="site"]');
await p.waitForSelector('[data-m="go"]');
await p.screenshot({ path: out.replace('.png', '-site.png') });
await p.tap('[data-m="go"]');
await p.waitForTimeout(+waitMs);
await p.screenshot({ path: out });
console.log(errs.slice(0, 20).join('\n'));
await b.close();
